var deck = [	
	{
	"name":"arbor_colossus",
	"frontSrc":"arbor_colossus",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"arbor_colossus",
	"frontSrc":"arbor_colossus",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"arbor_colossus",
	"frontSrc":"arbor_colossus",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"arbor_colossus",
	"frontSrc":"arbor_colossus",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"birds_of_paradise",
	"frontSrc":"birds_of_paradise",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"birds_of_paradise",
	"frontSrc":"birds_of_paradise",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"birds_of_paradise",
	"frontSrc":"birds_of_paradise",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"birds_of_paradise",
	"frontSrc":"birds_of_paradise",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"dungrove_elder",
	"frontSrc":"dungrove_elder",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"dungrove_elder",
	"frontSrc":"dungrove_elder",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"dungrove_elder",
	"frontSrc":"dungrove_elder",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"dungrove_elder",
	"frontSrc":"dungrove_elder",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"obstinate_baloth",
	"frontSrc":"obstinate_baloth",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"obstinate_baloth",
	"frontSrc":"obstinate_baloth",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"obstinate_baloth",
	"frontSrc":"obstinate_baloth",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"obstinate_baloth",
	"frontSrc":"obstinate_baloth",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"polukranos_world_eater",
	"frontSrc":"polukranos_world_eater",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"polukranos_world_eater",
	"frontSrc":"polukranos_world_eater",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"primeval_titan",
	"frontSrc":"primeval_titan",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"primeval_titan",
	"frontSrc":"primeval_titan",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"primeval_titan",
	"frontSrc":"primeval_titan",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"primeval_titan",
	"frontSrc":"primeval_titan",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"vorapede",
	"frontSrc":"vorapede",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"vorapede",
	"frontSrc":"vorapede",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"voyaging_satyr",
	"frontSrc":"voyaging_satyr",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"voyaging_satyr",
	"frontSrc":"voyaging_satyr",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"voyaging_satyr",
	"frontSrc":"voyaging_satyr",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"voyaging_satyr",
	"frontSrc":"voyaging_satyr",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"wasteland_viper",
	"frontSrc":"wasteland_viper",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"wasteland_viper",
	"frontSrc":"wasteland_viper",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"wasteland_viper",
	"frontSrc":"wasteland_viper",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"mosswort_bridge",
	"frontSrc":"mosswort_bridge",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"mosswort_bridge",
	"frontSrc":"mosswort_bridge",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"mosswort_bridge",
	"frontSrc":"mosswort_bridge",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"mosswort_bridge",
	"frontSrc":"mosswort_bridge",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"cultivate",
	"frontSrc":"cultivate",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"cultivate",
	"frontSrc":"cultivate",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"garruk_caller_of_beasts",
	"frontSrc":"garruk_caller_of_beasts",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"garruk_caller_of_beasts",
	"frontSrc":"garruk_caller_of_beasts",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"garruk_caller_of_beasts",
	"frontSrc":"garruk_caller_of_beasts",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"forest1",
	"frontSrc":"forest1",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"forest1",
	"frontSrc":"forest1",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"forest1",
	"frontSrc":"forest1",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"forest1",
	"frontSrc":"forest1",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"forest2",
	"frontSrc":"forest2",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"forest2",
	"frontSrc":"forest2",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"forest2",
	"frontSrc":"forest2",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"forest2",
	"frontSrc":"forest2",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"forest3",
	"frontSrc":"forest3",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"forest3",
	"frontSrc":"forest3",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"forest3",
	"frontSrc":"forest3",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"forest3",
	"frontSrc":"forest3",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"forest4",
	"frontSrc":"forest4",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"forest4",
	"frontSrc":"forest4",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"forest4",
	"frontSrc":"forest4",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"forest4",
	"frontSrc":"forest4",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"forest5",
	"frontSrc":"forest5",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"forest5",
	"frontSrc":"forest5",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"forest5",
	"frontSrc":"forest5",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"forest5",
	"frontSrc":"forest5",
	"backSrc":"",
	"dblsided":""
	}
]

module.exports = deck;