var deck = [	
	{
	"name":"chandras_outrage",
	"frontSrc":"chandras_outrage",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"chandras_outrage",
	"frontSrc":"chandras_outrage",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"fiery_impulse",
	"frontSrc":"fiery_impulse",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"fiery_impulse",
	"frontSrc":"fiery_impulse",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"lightning_bolt",
	"frontSrc":"lightning_bolt",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"lightning_bolt",
	"frontSrc":"lightning_bolt",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"lightning_bolt",
	"frontSrc":"lightning_bolt",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"lightning_bolt",
	"frontSrc":"lightning_bolt",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"shock",
	"frontSrc":"shock",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"shock",
	"frontSrc":"shock",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"shock",
	"frontSrc":"shock",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"oath_of_chandra",
	"frontSrc":"oath_of_chandra",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"oath_of_chandra",
	"frontSrc":"oath_of_chandra",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"chandras_phoenix",
	"frontSrc":"chandras_phoenix",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"chandras_phoenix",
	"frontSrc":"chandras_phoenix",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"chandras_phoenix",
	"frontSrc":"chandras_phoenix",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"chandras_phoenix",
	"frontSrc":"chandras_phoenix",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"fire_servant",
	"frontSrc":"fire_servant",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"fire_servant",
	"frontSrc":"fire_servant",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"fire_servant",
	"frontSrc":"fire_servant",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"pyre_hound",
	"frontSrc":"pyre_hound",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"pyre_hound",
	"frontSrc":"pyre_hound",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"pyre_hound",
	"frontSrc":"pyre_hound",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"pyre_hound",
	"frontSrc":"pyre_hound",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"satyr_firedancer",
	"frontSrc":"satyr_firedancer",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"pyromancers_gauntlet",
	"frontSrc":"pyromancers_gauntlet",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"flames_of_the_firebrand",
	"frontSrc":"flames_of_the_firebrand",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"flames_of_the_firebrand",
	"frontSrc":"flames_of_the_firebrand",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"flames_of_the_firebrand",
	"frontSrc":"flames_of_the_firebrand",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"lava_spike",
	"frontSrc":"lava_spike",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"lava_spike",
	"frontSrc":"lava_spike",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"lava_spike",
	"frontSrc":"lava_spike",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"lava_spike",
	"frontSrc":"lava_spike",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"roast",
	"frontSrc":"roast",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"roast",
	"frontSrc":"roast",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"roast",
	"frontSrc":"roast",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"chandra_pyromaster",
	"frontSrc":"chandra_pyromaster",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"chandra_the_firebrand",
	"frontSrc":"chandra_the_firebrand",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"chandra_the_firebrand",
	"frontSrc":"chandra_the_firebrand",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"mountain1",
	"frontSrc":"mountain1",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"mountain1",
	"frontSrc":"mountain1",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"mountain1",
	"frontSrc":"mountain1",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"mountain1",
	"frontSrc":"mountain1",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"mountain1",
	"frontSrc":"mountain1",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"mountain2",
	"frontSrc":"mountain2",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"mountain2",
	"frontSrc":"mountain2",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"mountain2",
	"frontSrc":"mountain2",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"mountain2",
	"frontSrc":"mountain2",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"mountain3",
	"frontSrc":"mountain3",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"mountain3",
	"frontSrc":"mountain3",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"mountain3",
	"frontSrc":"mountain3",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"mountain3",
	"frontSrc":"mountain3",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"mountain4",
	"frontSrc":"mountain4",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"mountain4",
	"frontSrc":"mountain4",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"mountain4",
	"frontSrc":"mountain4",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"mountain4",
	"frontSrc":"mountain4",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"mountain5",
	"frontSrc":"mountain5",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"mountain5",
	"frontSrc":"mountain5",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"mountain5",
	"frontSrc":"mountain5",
	"backSrc":"",
	"dblsided":""
	},
	{
	"name":"mountain5",
	"frontSrc":"mountain5",
	"backSrc":"",
	"dblsided":""
	}
]

module.exports = deck;